# Generated by Django 3.2.25 on 2025-02-20 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhatkysukien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Hethong_Thietbi', models.TextField(blank=True)),
                ('Hientuong_Dienbien', models.TextField(blank=True)),
                ('Quatrinh_Kt', models.TextField(blank=True)),
                ('LoaiSc', models.TextField(blank=True)),
                ('Baocao_Chidao', models.TextField(blank=True)),
                ('DeNghi', models.TextField(blank=True)),
                ('CaVanHanh', models.TextField(blank=True)),
                ('Donvi_khacPhuc', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
