# Generated by Django 3.2.25 on 2025-02-20 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250220_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xulysukientb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('Tomay', models.CharField(max_length=255)),
                ('Noidung_xuly', models.TextField(blank=True)),
                ('Thoigian_xuly', models.DateTimeField(blank=True, null=True)),
                ('Quatrinh_kiemtra', models.TextField(blank=True)),
                ('Dexuat_lienquan', models.TextField(blank=True)),
                ('Chidao', models.TextField(blank=True)),
                ('Tinhtrang_xuly', models.TextField(blank=True)),
                ('Quatrinh_Xuly', models.TextField(blank=True)),
                ('Phantich_Nguyennhan_Xl', models.TextField(blank=True)),
                ('Donvi_ghinhan', models.TextField(blank=True)),
                ('Cavanhanh_ghinhan', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nhatkysukien',
            name='xulysukientbs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.xulysukientb'),
        ),
    ]
