# Generated by Django 3.2.25 on 2025-02-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250220_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xulysukientb',
            old_name='title',
            new_name='name',
        ),
    ]
