# Generated by Django 3.2.25 on 2025-02-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250221_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhatkysukien',
            name='xulysukientbs',
        ),
        migrations.AddField(
            model_name='xulysukientb',
            name='nhatkysukien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xulysukientbs', to='core.nhatkysukien'),
        ),
    ]
