# Generated by Django 3.2.25 on 2025-02-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20250221_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xulysukientb',
            name='nhatkysukien',
        ),
        migrations.AddField(
            model_name='nhatkysukien',
            name='xulysukientbs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.xulysukientb'),
        ),
    ]
