# Generated by Django 3.2.25 on 2025-02-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20250222_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhatkysukien',
            name='xulysukientbs',
        ),
        migrations.AddField(
            model_name='nhatkysukien',
            name='xulysukientbs',
            field=models.ManyToManyField(blank=True, to='core.Xulysukientb'),
        ),
    ]
